### ISSUE TITLE
Conflicting stylization of tpy

### ISSUE THREAD

**Issue by liamhtml** [insyri/tpy#8]
Is it be "Tpy" or "tpy"? I've seen both in documentation. A convention should probably be established and stuck with.

**Comment by insyri** [comment]
Earlier on I wanted to stick with a lowercase stylization and only used Tpy for referencing the class. I didn't notice how conflicting this would be with regular use, like begining a sentence with 'tpy'.

It is stylized as Tpy going forward.

**Comment by liamhtml** [comment]
Are you planning to rename the repository?

**Comment by insyri** [comment]
No, but the title in the readme will be. I have little time right now since I'm about to start testing within the next ~10 minutes.

**Comment by insyri** [comment]
Resolved by #10
